
library(caret)
library(e1071)
library(Hmisc)
library(corrplot)
library(plyr)
library(pROC)
stroke<- read.csv('c:\\maha\\503\\healthcare-dataset-stroke-data.csv', header = TRUE)
str(stroke)
dim(stroke)
hist.data.frame(stroke)
skewness(stroke$avg_glucose_level)
skewness(stroke$age)
table(stroke$gender)
table(stroke$hypertension)
table(stroke$heart_disease)
table(stroke$ever_married)
table(stroke$work_type)
table(stroke$Residence_type)
table(stroke$smoking_status)
table(stroke$stroke)
stroke$gender <- as.numeric(as.factor(stroke$gender))
stroke$ever_married <- as.numeric(as.factor(stroke$ever_married))
stroke$work_type <- as.numeric(as.factor(stroke$work_type))
stroke$Residence_type <- as.numeric(as.factor(stroke$Residence_type))
stroke$smoking_status <- as.numeric(as.factor(stroke$smoking_status))
stroke$bmi <- as.numeric(stroke$bmi)
#stroke$stroke <- as.factor(stroke$stroke)
str(stroke)
corrplot(cor(stroke))
boxplot(stroke[,-1])



